package local:module;

interface module {
    record range {
        start: u32,
        end: u32,
    }

    variant print-part {
        str(string),
        new-line(u32),
        name,
        literal,
        keyword,
        %type,
        comment,
        reset,
        xref(definition-id),
    }

    record local-id {
        %func: u32,
        local: u32,
    }

    variant definition-id {
        %type(u32),
        %func(u32),
        table(u32),
        memory(u32),
        global(u32),
        element(u32),
        data(u32),
        local(local-id),
        tag(u32),
    }

    record item {
        range: range,
        raw-name: string,
        display-name: string,
        definition-id: option<definition-id>,
    }

    record validate-error {
        message: string,
        offset: u32,
    }

    resource module {
        constructor(init: list<u8>);

        validate: func() -> option<validate-error>;

        source: func() -> list<u8>;

        print-rich: func(id: option<definition-id>) -> result<list<print-part>, string>;
        print-plain: func(id: option<definition-id>) -> result<string, string>;

        items: func() -> list<item>;
    }
}

world wasm-tools {
    export module;
}
