package local:module;

interface module {
    record range {
        start: u32,
        end: u32,
    }

    variant print-part {
        str(string),
        new-line,
        name,
        literal,
        keyword,
        %type,
        comment,
        reset,
    }

    record item {
        range: range,
        name: string,
    }

    resource module {
        constructor(init: list<u8>);

        print-rich: func(range: range) -> result<list<print-part>, string>;
        print-plain: func(range: range) -> result<string, string>;
        items: func() -> list<item>;
    }
}

world wasm-tools {
    export module;
}
