// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod local {
        pub mod module {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod module {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Range {
                    pub start: u32,
                    pub end: u32,
                }
                impl ::core::fmt::Debug for Range {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Range")
                            .field("start", &self.start)
                            .field("end", &self.end)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub enum PrintPart {
                    Str(_rt::String),
                    NewLine,
                    Name,
                    Literal,
                    Keyword,
                    Type,
                    Comment,
                    Reset,
                }
                impl ::core::fmt::Debug for PrintPart {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            PrintPart::Str(e) => {
                                f.debug_tuple("PrintPart::Str").field(e).finish()
                            }
                            PrintPart::NewLine => {
                                f.debug_tuple("PrintPart::NewLine").finish()
                            }
                            PrintPart::Name => f.debug_tuple("PrintPart::Name").finish(),
                            PrintPart::Literal => {
                                f.debug_tuple("PrintPart::Literal").finish()
                            }
                            PrintPart::Keyword => {
                                f.debug_tuple("PrintPart::Keyword").finish()
                            }
                            PrintPart::Type => f.debug_tuple("PrintPart::Type").finish(),
                            PrintPart::Comment => {
                                f.debug_tuple("PrintPart::Comment").finish()
                            }
                            PrintPart::Reset => {
                                f.debug_tuple("PrintPart::Reset").finish()
                            }
                        }
                    }
                }
                #[derive(Clone)]
                pub struct Item {
                    pub range: Range,
                    pub name: _rt::String,
                }
                impl ::core::fmt::Debug for Item {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Item")
                            .field("range", &self.range)
                            .field("name", &self.name)
                            .finish()
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Module {
                    handle: _rt::Resource<Module>,
                }
                type _ModuleRep<T> = Option<T>;
                impl Module {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Module`.
                    pub fn new<T: GuestModule>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ModuleRep<T> = Some(val);
                        let ptr: *mut _ModuleRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestModule>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestModule>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestModule>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _ModuleRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestModule>(&self) -> *mut _ModuleRep<T> {
                        Module::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Module`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ModuleBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Module>,
                }
                impl<'a> ModuleBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestModule>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ModuleRep<T> {
                        Module::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Module {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(wasm_import_module = "[export]local:module/module")]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]module"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_module_cabi<T: GuestModule>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = Module::new(
                        T::new(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0)),
                    );
                    (result1).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_module_print_rich_cabi<T: GuestModule>(
                    arg0: *mut u8,
                    arg1: i32,
                    arg2: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::print_rich(
                        unsafe { ModuleBorrow::lift(arg0 as u32 as usize) }.get(),
                        Range {
                            start: arg1 as u32,
                            end: arg2 as u32,
                        },
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = e;
                            let len3 = vec3.len();
                            let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec3.len() * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result3 = if layout3.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout3);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec3.into_iter().enumerate() {
                                let base = result3
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    match e {
                                        PrintPart::Str(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let vec2 = (e.into_bytes()).into_boxed_slice();
                                            let ptr2 = vec2.as_ptr().cast::<u8>();
                                            let len2 = vec2.len();
                                            ::core::mem::forget(vec2);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len2;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr2.cast_mut();
                                        }
                                        PrintPart::NewLine => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                        }
                                        PrintPart::Name => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                        }
                                        PrintPart::Literal => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                        }
                                        PrintPart::Keyword => {
                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                        }
                                        PrintPart::Type => {
                                            *base.add(0).cast::<u8>() = (5i32) as u8;
                                        }
                                        PrintPart::Comment => {
                                            *base.add(0).cast::<u8>() = (6i32) as u8;
                                        }
                                        PrintPart::Reset => {
                                            *base.add(0).cast::<u8>() = (7i32) as u8;
                                        }
                                    }
                                }
                            }
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result3;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_module_print_rich<T: GuestModule>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base6 = l1;
                            let len6 = l2;
                            for i in 0..len6 {
                                let base = base6
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = i32::from(*base.add(0).cast::<u8>());
                                    match l3 {
                                        0 => {
                                            let l4 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l5 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l4, l5, 1);
                                        }
                                        1 => {}
                                        2 => {}
                                        3 => {}
                                        4 => {}
                                        5 => {}
                                        6 => {}
                                        _ => {}
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base6,
                                len6 * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l7 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l7, l8, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_module_print_plain_cabi<T: GuestModule>(
                    arg0: *mut u8,
                    arg1: i32,
                    arg2: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::print_plain(
                        unsafe { ModuleBorrow::lift(arg0 as u32 as usize) }.get(),
                        Range {
                            start: arg1 as u32,
                            end: arg2 as u32,
                        },
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_module_print_plain<T: GuestModule>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_module_items_cabi<T: GuestModule>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::items(
                        unsafe { ModuleBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let Item { range: range2, name: name2 } = e;
                            let Range { start: start3, end: end3 } = range2;
                            *base.add(0).cast::<i32>() = _rt::as_i32(start3);
                            *base.add(4).cast::<i32>() = _rt::as_i32(end3);
                            let vec4 = (name2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_module_items<T: GuestModule>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(8).cast::<*mut u8>();
                            let l3 = *base
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                pub trait Guest {
                    type Module: GuestModule;
                }
                pub trait GuestModule: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(wasm_import_module = "[export]local:module/module")]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]module"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(wasm_import_module = "[export]local:module/module")]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]module"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new(init: _rt::Vec<u8>) -> Self;
                    fn print_rich(
                        &self,
                        range: Range,
                    ) -> Result<_rt::Vec<PrintPart>, _rt::String>;
                    fn print_plain(
                        &self,
                        range: Range,
                    ) -> Result<_rt::String, _rt::String>;
                    fn items(&self) -> _rt::Vec<Item>;
                }
                #[doc(hidden)]
                macro_rules! __export_local_module_module_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "local:module/module#[constructor]module")] unsafe extern "C" fn
                        export_constructor_module(arg0 : * mut u8, arg1 : usize,) -> i32
                        { unsafe { $($path_to_types)*::
                        _export_constructor_module_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Module > (arg0, arg1) } } #[unsafe (export_name =
                        "local:module/module#[method]module.print-rich")] unsafe extern
                        "C" fn export_method_module_print_rich(arg0 : * mut u8, arg1 :
                        i32, arg2 : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_module_print_rich_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0, arg1, arg2) } }
                        #[unsafe (export_name =
                        "cabi_post_local:module/module#[method]module.print-rich")]
                        unsafe extern "C" fn _post_return_method_module_print_rich(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_module_print_rich::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0) } } #[unsafe
                        (export_name = "local:module/module#[method]module.print-plain")]
                        unsafe extern "C" fn export_method_module_print_plain(arg0 : *
                        mut u8, arg1 : i32, arg2 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_module_print_plain_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0, arg1, arg2) } }
                        #[unsafe (export_name =
                        "cabi_post_local:module/module#[method]module.print-plain")]
                        unsafe extern "C" fn _post_return_method_module_print_plain(arg0
                        : * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_module_print_plain::<<$ty as
                        $($path_to_types)*:: Guest >::Module > (arg0) } } #[unsafe
                        (export_name = "local:module/module#[method]module.items")]
                        unsafe extern "C" fn export_method_module_items(arg0 : * mut u8,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_module_items_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Module > (arg0) } } #[unsafe (export_name =
                        "cabi_post_local:module/module#[method]module.items")] unsafe
                        extern "C" fn _post_return_method_module_items(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*::
                        __post_return_method_module_items::<<$ty as $($path_to_types)*::
                        Guest >::Module > (arg0) } } const _ : () = { #[doc(hidden)]
                        #[unsafe (export_name = "local:module/module#[dtor]module")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: Module::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::Module > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_local_module_module_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_wasm_tools_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::local::module::module::__export_local_module_module_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::local::module::module);
    };
}
#[doc(inline)]
pub(crate) use __export_wasm_tools_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:local:module:wasm-tools:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 537] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x98\x03\x01A\x02\x01\
A\x02\x01B\x16\x01r\x02\x05starty\x03endy\x04\0\x05range\x03\0\0\x01q\x08\x03str\
\x01s\0\x08new-line\0\0\x04name\0\0\x07literal\0\0\x07keyword\0\0\x04type\0\0\x07\
comment\0\0\x05reset\0\0\x04\0\x0aprint-part\x03\0\x02\x01r\x02\x05range\x01\x04\
names\x04\0\x04item\x03\0\x04\x04\0\x06module\x03\x01\x01p}\x01i\x06\x01@\x01\x04\
init\x07\0\x08\x04\0\x13[constructor]module\x01\x09\x01h\x06\x01p\x03\x01j\x01\x0b\
\x01s\x01@\x02\x04self\x0a\x05range\x01\0\x0c\x04\0\x19[method]module.print-rich\
\x01\x0d\x01j\x01s\x01s\x01@\x02\x04self\x0a\x05range\x01\0\x0e\x04\0\x1a[method\
]module.print-plain\x01\x0f\x01p\x05\x01@\x01\x04self\x0a\0\x10\x04\0\x14[method\
]module.items\x01\x11\x04\0\x13local:module/module\x05\0\x04\0\x17local:module/w\
asm-tools\x04\0\x0b\x10\x01\0\x0awasm-tools\x03\0\0\0G\x09producers\x01\x0cproce\
ssed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
