name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - uses: cargo-bins/cargo-binstall@v1.6.9
      - run: cargo binstall cargo-component@0.20.0 -y
      - run: rustup component add rustfmt # needed for cargo-component, apparently?
      - run: rustup target add wasm32-wasip1
      - run: npm ci
      - run: npm run build

      # also prepare to deploy GH pages on main
      - if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "/dist"

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'eqrion'
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
